name: Build Modules
on:
  workflow_call:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get version
        id: ver
        run: echo "VER=$(date +%Y.%m.%d)" >> $GITHUB_OUTPUT

      - name: Make build.sh executable
        run: chmod +x build.sh
      
      - name: Build
        run: ./build.sh config.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*
          file_glob: true
          tag: ${{ steps.ver.outputs.VER }}
          release_name: Weekly Build ${{ steps.ver.outputs.VER }}
          overwrite: true
